# Generated by Django 3.2.4 on 2024-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
